
<?php

if(isset($_GET['msg'])) {
    $msg = $_GET['msg'];
    if($msg == 'logout') $aviso = "Usuário deslogado com sucesso";
    //elseif()
    ?>
        <div class="alert alert-success text-center">
            <?=$aviso?>
        </div>
    <?php
}

if(isset($_GET['cad_prof'])) {
    ?>
        <div class="alert alert-success text-center">
            Cadastro realizado com sucesso. Seu curriculo foi enviado.
        </div>
    <?php
}

if(isset($_GET['edit_perfil'])) {
    ?>
        <div class="alert alert-success text-center">
            Seu perfil foi alterado com sucesso.
        </div>
    <?php
}

if(isset($_GET['pedido'])) {
    ?>
        <div class="alert alert-success text-center">
            Seu Pedido foi realizado.
        </div>
    <?php
}

if(isset($_GET['edit'])) {
    ?>
        <div class="alert alert-success text-center">
            Seu Pedido foi alterado com sucesso.
        </div>
    <?php
}

if(isset($this->view->pedidos)) { ?> 
    <div> 
        <div class="mt-2 h3 text-center">Pedidos <?="de: ".$this->view->nome?> Abertos</div>

        <div class="mt-4 d-flex justify-content-evenly">
            <?php foreach($this->view->pedidos as $value) { ?>
                <a href="/ver_pedido?id=<?=$value['id']?>" class="btn btn-info">Pedido: <br><?=$value['data_solicitacao']?></a>
            <?php } ?>
    
        </div>
    </div>
<?php } ?>

<div class="position-absolute top-50 start-50 translate-middle">
    <a href="fazer_pedido" class="btn btn-success">Fazer Pedido</a>
</div>

