

<?php

if(isset($_GET['cad_prof'])) {
    ?>
        <div class="alert alert-success text-center">
            Cadastro realizado com sucesso. Seu curriculo foi enviado.
        </div>
    <?php
}

?>

<!--<div class="m-0 p-0 text-center my-5">
    <div class="mb-5 h1">Página Principal</div>
    <a href="profissional" class="btn btn-primary">Quero ser um profissional</a>
</div>

<div class="m-0 p-0 text-center my-5">
    <a href="login" class="btn btn-primary">Login</a>
</div>

<div class="m-0 p-0 text-center my-5">
    <a href="avaliar" class="btn btn-primary">Avaliar</a>
</div>-->