<div class="text-center mt-5">
    <div class="display-4 fw-bold">
        <span class="text-info">Lorem ipsum</span> dolor sit amet
        <br>
        consectetur adipiscing elit
    </div>
    <div class="h4 my-4">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis interdum mollis lorem, ut porta tortor <br>
        accumsan a. Donec at nibh
    </div>
    <a href="/" class="btn btn-info rounded-4 h5 px-3 py-2">Conheça nosso site!</a>
</div>

<div class="container text-center mb-5">
    <div></div>
</div>

<div class="container mb-5 text-center" style="width: 70%;">
    <div id="h1">
        <h1 class="mb-3">O que é a InstantService?</h1>
    </div>
    <div class="h5">
    A InstantService é uma plataforma digital inovadora que conecta clientes a profissionais de tecnologia qualificados de maneira rápida, segura e acessível. Nosso objetivo é simplificar o processo de busca e contratação de serviços técnicos, oferecendo uma solução prática para empresas e residências.
    <br> <br>
    Com funcionalidades como agendamento online, avaliações de clientes e pagamento integrado, garantimos conveniência e confiança para nossos usuários. Na InstantService, acreditamos em unir eficiência tecnológica com atendimento de qualidade para resolver as necessidades do dia a dia de forma inteligente e eficaz.
    </div>
</div>

<div class="m-0 p-0 row d-flex justify-content-around my-5">
    <div class="col-3 m-0 p-0">
        <div class="bg-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
    <div class="col-3 m-0 p-0">
        <div class="border border-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
    <div class="col-3 m-0 p-0">
        <div class="bg-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
</div>

<div class="container text-center my-5" style="width: 70%;">
    <div id="h1">
        <h1 class="mb-3">Como a InstantService funciona para o Profissional?</h1>
    </div>
    <div class="h5">
    A InstantService é a parceira ideal para profissionais de tecnologia que desejam expandir sua clientela e simplificar sua rotina.
    <br> <br>
    Ao se cadastrar na plataforma, você cria um perfil profissional detalhado, destacando suas habilidades e especializações. Quando um cliente solicita um serviço que corresponde às suas competências, você recebe a solicitação diretamente.
    <br> <br>
    Com funcionalidades como agendamento integrado, comunicação facilitada e sistema de avaliação, a InstantService permite que você gerencie suas demandas de forma eficiente, garantindo maior visibilidade e recorrência de clientes. É a maneira mais fácil de focar no que você faz de melhor: entregar resultados!
    </div>
</div>

<div class="m-0 p-0 row d-flex justify-content-around my-3">
    <div class="col-3 m-0 p-0">
        <div class="border border-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
    <div class="col-3 m-0 p-0">
        <div class="bg-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
    <div class="col-3 m-0 p-0">
        <div class="border border-info w-75 m-auto rounded-3 text-center" style="height: 200px;"></div>
    </div>
</div>


<div class="container text-center my-5">
    <div id="h1">
        <h1>Sobre nós</h1>
    </div>
</div>

<div class="row mb-5 m-0 d-flex justify-content-center">
    <div class="col-5 text-end"> <img class="img-fluid" src="/public/assets/img/equipe.jpg" alt="" style="max-width: 500px;"> </div>

    <div class="col-5 h5 text-black text-start align-self-center">
    A InstantService nasceu com o propósito de conectar pessoas e soluções tecnológicas de forma prática e eficiente. Em um mundo onde a tecnologia está em constante evolução, percebemos a necessidade de uma ponte confiável entre clientes que buscam suporte técnico e profissionais capacitados que desejam expandir sua atuação.
    <br> <br>
    Nossa plataforma oferece muito mais do que uma simples conexão. Com funcionalidades como agendamento online, avaliações transparentes e pagamento integrado, trabalhamos para tornar a experiência de contratar e prestar serviços técnicos mais simples, segura e acessível.
    <br> <br>
    Acreditamos no poder da tecnologia para aproximar pessoas, resolver problemas e criar oportunidades. Seja você um cliente em busca de soluções ou um profissional à procura de novos desafios, a InstantService é o lugar certo para transformar essas necessidades em resultados. Junte-se a nós e descubra como podemos facilitar seu dia a dia!

    </div>
</div>