<div class="my-5 h1 text-center">Lista de Funcionários</div>

<div class="m-3">
    <div class="mb-4 text-start">
        <a href="/funcionario_cadastro" class="btn btn-dark p-3 border border-dark border-2 rounded-5"> Cadastrar Funcionario </a>
    </div>

    <table class="table table-bordered table-striped ">
        <thead>
            <tr>
                <th scope="col">Nome Completo</th>
                <th scope="col">Email</th>
                <th scope="col">Data de Nascimento</th>
                <th scope="col">CPF</th>
                <th scope="col">Sexo</th>
                <th scope="col">Tipo</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody> 
            <?php foreach($this->view->funcionarios as $value) { ?>
                <tr>
                    <td><?=$value['nome_completo']?></td>
                    <td><?=$value['email']?></td>
                    <td><?=$value['data_nascimento']?></td>
                    <td><?=$value['cpf']?></td>
                    <td><?=$value['sexo']?></td>
                    <td><?=($value['tipo']==3)?"Funcionário":"Gerente"?></td>
                    <td><a onclick="return confirmar_exclusao()" href="excluir_funcionario?id=<?=$value['id_cliente']?>" class="btn btn-danger">Deletar Funcionário</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>