<div class="my-5 display-2 text-center">Lista em Atendimento </div>

<div class="m-3">
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th scope="col">Solicitante</th>
                <th scope="col">Problema</th>
                <th scope="col">Descrição</th>
                <th scope="col">Endereço</th>
                <th scope="col">Data da Solicitação</th>
                <th scope="col">Sistema</th>
            </tr>
        </thead>
        <tbody> 
            <?php foreach($this->view->pedidos as $value) { ?>
                <tr>
                    <td><?=$value['nome_completo']?></td>
                    <td><?=$value['problema']?></td>
                    <td><?=$value['descricao']?></td>
                    <td><?=$value['endereco']?></td>
                    <td><?=$value['data_solicitacao']?></td>
                    <td><a href="" class="btn shadow text-start ">Mais Informações</a> <a href="" class="btn shadow text-start ">Recusar Pedido</a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
