<div class="row m-auto mt-5 col-10 shadow p-2 pe-4 rounded-4">
    <div class="col col-12 my-3 ps-3">
        <span class="h3 text-decoration-underline fw-bold">Cadastro de funcionário</span>
        <form class="col row mt-3" action="cadastrar_funcionario" method="POST">
            <div class="mb-3 col col-sm-6 col-12">
                <label for="nome" class="form-label">Nome</label> 
                <input type="text" class="form-control" id="nome" placeholder="Nome" name="nome" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="sobrenome" class="form-label">Sobrenome</label> 
                <input type="text" class="form-control" id="sobrenome" placeholder="Sobrenome" name="sobrenome" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="sexo" class="form-label">Sexo</label>
                <select class="form-select" id="sexo" name="sexo" required>
                    <option value="F">Feminino</option>
                    <option value="M">Masculino</option>
                    <option value="O">Outro</option>
                </select>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="data_nascimento" class="form-label">Data de Nascimento</label>
                <input type="date" class="form-control" id="data_nascimento" placeholder="Data de Nascimento" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="cpf" class="form-label">CPF</label>
                <input type="text" class="form-control" id="cpf" placeholder="CPF" name="cpf" oninput="mascara_cpf()" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Email" name="email" oninput="mascara_email()" required>
            </div>

            <span class="h3 text-decoration-underline fw-bold my-3">Informações de Login</span>
            <div class="col col-sm-6 col-12">
                <label for="login" class="form-label">Login</label> 
                <input type="text" class="form-control" id="login" placeholder="Login" name="login" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="tipo" class="form-label">Tipo</label> 
                <select class="form-select" id="tipo" name="tipo" required>
                    <option value="3">Funcionário</option>
                    <option value="4">Gerência</option>
                </select>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="senha" class="form-label">Senha</label> 
                <input type="password" class="form-control" id="senha" placeholder="Senha" name="senha" required>
            </div>
            <div class="mb-3 col col-sm-6 col-12">
                <label for="senha2" class="form-label">Confirme sua Senha</label> 
                <input type="password" class="form-control" id="senha2" placeholder="Confirme sua Senha" name="senha2" required>
            </div>

            <div class="mb-3 mt-4 col col-12 text-center">
                <a href="funcionario" class="btn btn-danger mx-1" style="min-width: 100px;"> Cancelar</a>
                <button type="submit" class="btn btn-success mx-1" style="min-width: 100px;"> Cadastrar</button>
            </div>
        </form>
    </div>
</div>