<?php 
    $profissional = $this->view->dados["profissional"];
    $dados = $this->view->dados["dados"];
    var_dump($dados);
?>

<div>

    <div id="div_camposusuario" class="m-0 row d-flex justify-content-center">
        <div class="h1 mb-5">Informações pessoais:</div>

        <div class="h3 col-5 row mb-4">
            <label class="pe-2 mb-1" for="name">Nome:</label>
            <input class="w-50" type="text" name="name" value="<?=$dados["nomecompleto"]?>">
        </div>

        <div class="h3 col-5 row mb-4">
            <label class="pe-2 mb-1" for="name">Email:</label>
            <input class="w-50" type="text" name="name">
        </div>

        <div class="h3 col-5 row mb-4">
            <label class="pe-2 mb-1" for="name">Sexo:</label>
            <input class="w-50" type="text" name="name">
        </div>

        <div class="h3 col-5 row mb-4">
            <label class="pe-2 mb-1" for="name">Nascimento:</label>
            <input class="w-50" type="text" name="name">
        </div>

        <div class="h3 col-5 row mb-4">
            <label class="pe-2 mb-1" for="name">CPF:</label>
            <input class="w-50" type="text" name="name">
        </div>
        <div class="h3 col-5 row mb-4"></div>


        <?php if($profissional) { ?>
            <div class="h1 mb-5">Informações profissionais:</div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>

            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>
            
            <div class="h3 col-5 row mb-4">
                <label class="pe-2 mb-1" for="name">Nome:</label>
                <input class="w-50" type="text" name="name">
            </div>
            <div class="h3 col-5 row mb-4"></div>
        <?php } ?>


    </div>

    <button>alterar dados pessoais</button>

</div>