<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?=$this->view->page?></title>
    <!-- Links -->
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <!-- select2 CSS -->
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <!-- select2 tema bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2-bootstrap-5-theme@1.3.0/dist/select2-bootstrap-5-theme.min.css" />
        <!-- google_fonts CSS -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
        <!--Internal CSS-->
        <link rel="stylesheet" href="/public/assets/css/style.css">
        <!--Font Awesome-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
        <!--Leaflet MAPA-->
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
</head>
<body class="bg-light">
    <nav class="navbar navbar-light bg-light border-bottom">
        <div class="container-fluid p-0">


            <button class="navbar-toggler ms-4" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="d-flex align-items-center mt-1" style="width: 200px; height: 0px;">
                <a href="/" class="h2 m-0 text-decoration-none">
                    <img class="img-fluid" src="/public/assets/img/logo_dark.png" alt="">
                </a>
            </div>

            <div class="nav-brand dropdown m-0 p-0">
                <a class="nav-link dropdown-toggle text-light d-flex justify-content-end m-0 p-0" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <div class="d-flex justify-content-end">
                        <?php if (isset($_SESSION['img']) && $_SESSION['img']) { ?>
                            <div class="d-flex align-items-center" style="width: 50px; height: 50px;">
                                <img class="rounded-circle img-fluid w-100 h-100 object-fit-cover shadow" src="/public/assets/img/img_perfil/<?=$_SESSION['img']?>" alt="">
                            </div>
                        <?php } else { ?>
                            <div class="d-flex align-items-center" style="width: 50px; height: 50px;">
                                <img class="rounded-circle img-fluid w-100 h-100 object-fit-cover" src="/public/assets/img/img_perfil/perfil0.png" alt="">
                            </div>
                        <?php } ?>
                    </div>
                </a>

                <ul class="dropdown-menu dropdown-menu dropdown-menu-end me-1">
                    <?php if(!isset($_SESSION['id'])) { ?>
                        <li class="nav-item">
                            <a class="nav-link ps-2" href="login">Login</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link ps-2" href="cadastrar">Cadastrar</a>
                        </li>
                    <?php } else { ?>
                        <li class="nav-item">
                            <a class="nav-link ps-2" href="perfil">Perfil</a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li class="nav-item">
                            <a class="nav-link ps-2" href="logout">Logout</a>
                        </li>
                    <?php } ?>
                </ul>
            </div>

            <div class="offcanvas offcanvas-start shadow-lg" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">InstantService</h5>
                    <button type="button" class="btn-close btn-close-dark" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item ">
                            <a class="nav-link" aria-current="page" href="/">Home</a>
                        </li>

                        <?php if(isset($_SESSION['tipo']) and $_SESSION['tipo']>=3){ ?>
                            <li class="nav-item ">
                                <a class="nav-link" href="avaliar">Avaliar</a>
                            </li>
                        <?php } ?>

                        <?php if(isset($_SESSION['tipo']) and $_SESSION['tipo']>=4){ ?>
                            <li class="nav-item ">
                                <a class="nav-link" href="funcionario">Funcionário</a>
                            </li> 
                        <?php } ?>

                        <li class="nav-item ">
                            <a class="nav-link" aria-current="page" href="/sobre_nos">Sobre Nós</a>
                        </li>

                        <?php if(isset($_SESSION['tipo']) and $_SESSION['tipo']<3){ ?>
                            <li class="nav-item ">
                                <a class="nav-link" href="profissional"><?=(isset($_SESSION['tipo']) and $_SESSION['tipo']==2)?"Area profissional":"Cadastrar como profissional"?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <div style="min-height: 59vh;">
        <?= $this->content() ?>
    </div>

    <footer class="bg-dark text-white-50 py-5">
        <div class="container">
            <div class="row justify-content-center">
                <!-- About Section -->
                <div class="col-md-3 mb-3 ">
                    <h5 class="text-white fw-bold">Sobre InstantService</h5>
                    <p class="text-white-50">Conectamos clientes a profissionais de tecnologia de maneira rápida, confiável e acessível. Soluções feitas para você!</p>
                </div>

                <!-- Quick Links -->
                <div class="col-md-2 mb-3">
                    <h5 class="text-white fw-bold">Links Úteis</h5>
                    <ul class="list-unstyled">
                        <li><a href="/" class="text-white-50 text-decoration-none">Home</a></li>
                        <li><a href="#" class="text-white-50 text-decoration-none">Serviços</a></li>
                        <li><a href="/sobre_nos" class="text-white-50 text-decoration-none">Sobre Nós</a></li>
                        <li><a href="#" class="text-white-50 text-decoration-none">Contato</a></li>
                    </ul>
                </div>

            <!-- Contact Section -->
                <div class="col-md-3 mb-3">
                    <h5 class="text-white fw-bold">Contato</h5>
                    <ul class="list-unstyled">
                        <li class="text-white-50"><i class="fa-solid fa-envelope text-white-50"></i> instantserviceapp@gmail.com</li>
                        <li class="text-white-50"><i class="fa-solid fa-phone text-white-50"></i> +55 31 1234-5678</li>
                        <li class="text-white-50"><i class="fa-solid fa-location-dot text-white-50"></i> Rua Exemplo, 123, Belo Horizonte</li>
                    </ul>
                    <div class="mt-3">
                        <a href="#" class="text-white-50 me-3"><i class="fa-brands fa-facebook text-white-50"></i></a>
                        <a href="#" class="text-white-50 me-3"><i class="fa-brands fa-twitter text-white-50"></i></a>
                        <a href="#" class="text-white-50 me-3"><i class="fa-brands fa-instagram text-white-50"></i></a>
                        <a href="#" class="text-white-50"><i class="fa-brands fa-linkedin text-white-50"></i></a>
                    </div>
                </div>

                <div class="col-md-3 mb-3">
                    <h5 class="text-white fw-bold">Deixe-nos te ajudar!</h5>
                    <ul class="list-unstyled">
                        <li><a href="/login" class="text-white-50 text-decoration-none">Entrar na sua Conta</a></li>
                        <li><a href="/" class="text-white-50 text-decoration-none">Ir para o Início</a></li>
                        <li><a href="/fazer_pedido" class="text-white-50 text-decoration-none">Fazer Pedido</a></li>
                        <li><a href="/profissional" class="text-white-50 text-decoration-none">Tornar-se Profissional</a></li>
                    </ul>
                </div>
            </div>

            <div class="text-center mt-4">
            <p class="mb-0 text-white-50">© 2024 InstantService. Todos os direitos reservados.</p>
            </div>
            
        </div>
    </footer>

    <!--jquery JS-->
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.js"></script>
    <!-- select2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <!--Leaflet MAPA-->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <!-- Internal JS -->
    <script src="/public/assets/js/ajax.js"></script>
    <script src="/public/assets/js/all.js"> </script>
    <script src="/public/assets/js/email.js"> </script>
    <script src="/public/assets/js/mapa.js"> </script>
</body>
</html>