<?php
    $avaliacao = (isset($this->view->dados))?$this->view->dados:"";
?>
<div class="position-absolute top-50 start-50 translate-middle m-0 p-0 text-center container-fluid">
    <div class="mb-5 display-3">O seu cadastro já foi concluído</div>

    <?php if(isset($avaliacao['mensagem'])) { ?>
        <h4 class="m-0">Resposta do nosso time:</h4>
        <div>
            <textarea disabled class="container mt-3 text-center"><?=$avaliacao['mensagem']?></textarea>
        </div>
        
    <?php } else { ?>
        <h4 class="m-0">Nosso time irá analisar seu perfil. Aguarde futuras respostas!</h4>
    <?php } ?>

    <button type="button" class="mt-5 btn btn-dark"><a class="text-decoration-none text-white" href="/">Voltar</a></button> 
</div>