<div class="m-0 p-0 text-center my-5 row">
    <h1 class="mb-5 display-2">Ver detalhes do pedido</h1>

    <div class="container col col-sm-4 col-11 py-2 h5 border px-5 border-5 rounded-3 border-dark mt-3">

        <div class="mt-2 mb-3 mx-auto row p-0" id="div_problemas" >
            <label for="id_problema" class="col mb-2 p-0 my-auto text-start">Problema:</label>
            <input type="text" class="p-1 my-auto text-start" value="<?=$this->view->info['nome']?>" disabled>
        </div>
            
        <div class="mt-2 mb-3 mx-auto row p-0" id="descricao">
            <label for="descricao" class="col mb-2 p-0 my-auto text-start">Descreva seu problema:</label>
            <textarea name="descricao" class="p-1 my-auto text-start" style="max-height: 150px; min-height: 48px;" disabled><?=$this->view->info['descricao']?></textarea>
        </div>

        <div class="mt-2 mb-3 mx-auto row p-0" id="endereco">
            <label for="endereco" class="col mb-2 p-0 my-auto text-start" >Endereço:</label>
            <input name="endereco" type="text" class="p-1 my-auto text-start" value="<?=$this->view->info['endereco']?>" disabled>
        </div>


        <div class="card">
            <div class="card-header">
                Chat
            </div>
            <div class="card-body chat-body" style="max-height: 200px; min-height: 200px; overflow-y: auto;">
                <?php $ult_msg = "";
                foreach($this->view->chat as $msg) { ?>
                    <?php if($msg['remetente'] == "U") {
                        $ps = "text-start ps-2";
                        $nome = $msg['nome_cliente'];
                    } else {
                        $ps = "text-end me-2";
                        $nome = $msg['nome_profissional'];
                    } ?>

                    <div class="<?=$ps?>">
                        <?php if($ult_msg != $nome) { $ult_msg = $nome; ?>
                            <div class="me-2"><?=$nome?></div>
                        <?php } ?>

                        <div class="py-2"><samp class="bg-secondary-subtle p-2 rounded-2"><?=$msg['mensagem']?></samp></div>

                    </div>
                <?php } ?>
            </div>
            <div class="card-footer">
                <div class="input-group">
                    <form action="cad_mensagem?id_pedido=<?=$_GET['id']?>&remetente=<?=$this->view->remetente?>&link=detalhes_pedido" method="POST" class="w-100">
                        <div class="row">
                            <div class="col-10">
                                <input type="text" class="form-control" name="msg" maxlength="255" placeholder="Digite sua mensagem aqui...">
                            </div>
                            
                            <div class="input-group-append col-2">
                                <button class="btn btn-success" type="submit">Enviar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    
    <div>
        <a href="/finalizar_pedido?id=<?=$_GET['id']?>" class="mt-5 btn btn-primary"> Finalizar Pedido </a>
        <a href="/profissional_pedidos_vinculados" class="mt-5 btn btn-primary"> Voltar </a>
    </div>
</div>