<?php if(isset($this->view->edit)) {
    ?>
        <div class="alert alert-success text-center">
            Cadastro realizado com sucesso. Seu curriculo foi enviado.
        </div>
    <?php
} ?>
<div class="m-0 p-0 text-center my-5 row">
    <h1 class="mb-5">Editar Pedido</h1>

    <form action="edit_pedido?id=<?=$this->view->info['id']?>" method="POST" class="row container col col-sm-4 col-11 m-auto py-2 h5 border px-5 border-5 rounded-3 border-dark">

        <div class="mt-2 mb-3 col-12 mx-auto row p-0" id="div_problemas" >
            <label for="id_problema" class="col mb-2 p-0 my-auto text-start">Problema:</label>
            <input type="text" value="<?=$this->view->info['nome']?>" disabled>
        </div>
            
        <div class="mt-2 mb-3 col-12 mx-auto row p-0" id="descricao" ">
            <label for="descricao" class="col mb-2 p-0 my-auto text-start">Descreva seu problema:</label>
            <textarea name="descricao" class="py-1" required><?=$this->view->info['descricao']?></textarea>
        </div>

        <div>
            <button type="submit" class="btn btn-success w-25" id="btnpedido"> Editar</button>
            <a href="excluir_pedido?id=<?=$this->view->info['id']?>" class="btn btn-danger w-25" id="btnpedido"> Excluir</a>
        </div>
    </form>

    <div>
        <a href="/" class="mt-5 btn btn-primary"> voltar </a>
    </div>
</div>