<div class="m-0 p-0 text-center my-5 row">
    <h1 class="mb-5">Login</h1>
    <form action="logar" method="POST" class="row container col col-sm-4 col-11 m-auto py-2 h5 border px-5  border-5 rounded-3 border-dark">  
        <div class="mt-3 mb-3 col-12 mx-auto row p-0">
            <label for="login" class="col mb-2 p-0 my-auto text-start">Login:</label>
            <input type="text" id="login" name="login" class="col-12 p-1" required> 
        </div>

        <div class="mt-2 mb-3 col-12 mx-auto row p-0">
            <label for="senha" class="col mb-2 p-0 my-auto text-start">Senha:</label>
            <input type="password" id="senha" name="senha" class="col-12 p-1" required> 
        </div>
        
        <div class="my-3 mx-auto p-0 text-center" id="troca_cad">
            <button type="submit" class="w-75 btn btn-success">Logar</button>
        </div>

        <div class="mb-4">
            <a href="cadastrar" class="text-decoration-none">Não possui uma conta? Cadastrar.</a>
        </div>

    </form>
</div>