<div class="row d-flex justify-content-center m-0 vh-100">
    <div class="col col-11 col-sm-3 my-auto p-0">
        <div class="mb-2 text-center h2">Entre com sua conta!</div>
        
        <form action="logar" method="POST" class="form container mt-3 m-auto py-2 h5 px-5 border-dark">  
            <div class="mt-3 mb-3 mx-auto p-0">
                <input type="text" id="login" name="login"     class="p-1 form-control rounded-pill ps-3 py-2" placeholder="Digite seu login aqui!" required> 
            </div>

            <div class="mt-2 mb-3 mx-auto row p-0">
                <input type="password" id="senha" name="senha" class="p-1 form-control rounded-pill ps-3 py-2" placeholder="Digite sua senha aqui!" required> 
            </div>
            
            <div class="my-3 mx-auto p-0 text-center" id="troca_cad">
                <button type="submit" class="w-100 btn btn-dark rounded-pill">Logar</button>
            </div>
            
            <div class="d-flex align-itens-center my-4">
                <hr class="flex-grow-1">
                <span class="mx-3">ou</span>
                <hr class="flex-grow-1">
            </div>

            <div class="text-center d-flex justify-content-center">
                <a href="<?=$this->authUrl?>" class="btn btn-light border  w-100 rounded-pill mb-3"><i class="fa-brands fa-google pe-2 text-dark" ></i>Fazer login com Google</a>
            </div>

            <div class="mb-4 text-center">
                <a href="cadastrar" class="btn btn-light border border w-100 rounded-pill">Sem conta? Cadastre-se!</a>
            </div>
        </form>
    </div>
</div>
